name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening your first issue on our repository. We will check it as soon as possible and get back to you.'' first issue'
        pr-message: 'Thanks for opening your first pr on our repository. We will check it as soon as possible and get back to you.'' first pr'
